services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: exchange-doc-db
    environment:
      POSTGRES_DB: exchange_docs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exchange-doc-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/exchange_docs
      UPLOAD_DIR: /app/uploads
      MAX_UPLOAD_SIZE: 52428800  # 50MB in bytes
      CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173"]'
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exchange-doc-frontend
    environment:
      VITE_API_URL: http://localhost:8000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  upload_data:
